export WANDB_DISABLED=true

python run_speech_recognition_ctc.py \
	--model_name_or_path="/home/sulcm/models/wav2vec2/wav2vec2-cs-pretrained" \
	--output_dir="/home/sulcm/models/wav2vec2/wav2vec2-cs-test/" \
	--overwrite_output_dir \
	--dataset_name="mozilla-foundation/common_voice_11_0" \
	--dataset_config_name="cs" \
	--text_column_name="sentence" \
	--audio_column_name="audio" \
	--train_split_name="train[:500]" \
	--eval_split_name="test[:100]" \
	--eval_metrics wer cer \
	--evaluation_strategy="steps" \
	--max_steps="500" \
	--learning_rate="5e-5" \
	--warmup_steps="100" \
	--chars_to_ignore , ? . ! - \; \: \" “ % ‘ ” � \
	--freeze_feature_encoder \
	--fp16 \
	--group_by_length \
	--do_train \
	--do_eval \
	--load_best_model_at_end=True \
	--metric_for_best_model="wer" \
	--greater_is_better=False \
	--per_device_train_batch_size="32" \
	--save_steps="1000" \
	--eval_steps="1000" \
	--logging_steps="10" \
	--save_total_limit="2" \
	--gradient_checkpointing